import { pgTable, integer, varchar, boolean } from "drizzle-orm/pg-core";

export const userTable = pgTable("user", {
    // ids
    account_id: integer().notNull().primaryKey(),
    user_id: integer().notNull(),

    // creds
    username: varchar({ length: 15 }).notNull(),
    email: varchar().notNull(),
    password: varchar().notNull(),
    custom: varchar().notNull(),
    is_registered: boolean().notNull(),

    // stats
    stars: integer().notNull(),
    moons: integer().notNull(),
    diamonds: integer().notNull(),
    demon_count: integer().notNull(),
    ranking: integer().notNull(),
    creator_points: integer().notNull(),
    secret_coins: integer().notNull(),
    user_coins: integer().notNull(),
    global_rank: integer().notNull(),

    // levels
    demons: varchar().notNull(),
    classic_levels: varchar().notNull(),
    platformer_levels: varchar().notNull(),

    // icons
    icon_id: integer().notNull(),
    icon_type: integer().notNull(),
    color: integer().notNull(),
    color2: integer().notNull(),
    color3: integer().notNull(),
    acc_icon: integer().notNull(),
    acc_ship: integer().notNull(),
    acc_ball: integer().notNull(),
    acc_bird: integer().notNull(),
    acc_dart: integer().notNull(),
    acc_robot: integer().notNull(),
    acc_spider: integer().notNull(),
    acc_swing: integer().notNull(),
    acc_jetpack: integer().notNull(),
    acc_streak: integer().notNull(),
    acc_glow: boolean().notNull(),
    acc_explosion: boolean().notNull(),
    special: integer().notNull(),

    // social
    message_state: integer().notNull(),
    friends_state: integer().notNull(),
    comment_history_state: integer().notNull(),
    youtube: varchar().notNull(),
    twitter: varchar().notNull(),
    twitch: varchar().notNull(),
    discord: varchar().notNull(),
    instagram: varchar().notNull(),
    tiktok: varchar().notNull(),

    // other
    mod: integer().notNull(),
    account_highlight: varchar().notNull(),
});

export const levelTable = pgTable("level", {
    level_id: integer().notNull().primaryKey(),
    level_name: varchar({ length: 20 }).notNull(),
    description: varchar(),
    level_string: varchar().notNull(),
    version: integer().notNull(),
    player_id: integer().notNull(),
    difficulty_denominator: integer().notNull(),
    difficulty_numerator: integer().notNull(),
    downloads: integer().notNull(),
    set_completes: integer().notNull(),
    official_song: integer(),
    game_version: integer().notNull(),
    likes: integer().notNull(),
    length: integer().notNull(),
    dislikes: integer().notNull(),
    demon: boolean().notNull(),
    stars: integer().notNull(),
    feature_score: integer().notNull(),
    star_ratings: integer().notNull(),
    star_ratings_sum: integer().notNull(),
    min_star_ratings: integer().notNull(),
    max_star_ratings: integer().notNull(),
    demon_votes: integer().notNull(),
    auto: boolean().notNull(),
    record_string: varchar().notNull(),
    password: varchar().notNull(),
    upload_date: varchar().notNull(),
    update_date: varchar().notNull(),
    copied_id: integer(),
    two_player: boolean().notNull(),
    rate_stars: integer().notNull(),
    rate_feature: boolean().notNull(),
    rate_user: varchar().notNull(),
    custom_song_id: integer(),
    extra_string: varchar(),
    coins: integer().notNull(),
    verified_coins: boolean().notNull(),
    stars_requested: integer().notNull(),
    low_detail_mode: integer().notNull(),
    daily_number: integer(),
    epic: integer().notNull(),
    demon_difficulty: integer().notNull(),
    is_gauntlet: boolean().notNull(),
    objects: integer().notNull(),
    editor_time: integer().notNull(),
    editor_time_copies: integer().notNull(),
    song_ids: integer().array(),
    sfx_ids: integer().array(),
    song_size: integer().notNull(),
    verification_time: integer().notNull(),
    exact_upload_time: integer().notNull(),
    exact_update_time: integer().notNull()
});

export const listTable = pgTable("list", {
    list_id: integer().notNull().primaryKey(),
    list_name: varchar({ length: 25 }).notNull(),
    description: varchar(),
    version: integer().notNull(),
    difficulty: integer().notNull(),
    downloads: integer().notNull(),
    likes: integer().notNull(),
    rated: boolean().notNull(),
    upload_date: varchar().notNull(),
    update_date: varchar().notNull(),
    account_id: integer().references(() => userTable.account_id).notNull(),
    username: varchar().references(() => userTable.username).notNull(),
    level_ids: integer().references(() => levelTable.level_id).array().notNull(),
    list_reward: integer().notNull(),
    list_reward_requirement: integer().notNull()
});