import { pgTable, serial, integer, bigint, varchar, boolean } from "drizzle-orm/pg-core";

import { user } from "@server/db/schema/user";

export const level = pgTable("level", {
    level_id: serial().notNull().primaryKey(),
    level_name: varchar({ length: 20 }).notNull(),
    description: varchar().notNull().default(""),
    level_string: varchar().notNull(),
    version: integer().notNull(),
    player_id: integer().notNull().references(() => user.account_id),
    difficulty_denominator: integer().notNull().default(0),
    difficulty_numerator: integer().notNull().default(0),
    downloads: integer().notNull().default(0),
    official_song: integer(),
    game_version: integer().notNull(),
    likes: integer().notNull().default(0),
    length: integer().notNull(),
    dislikes: integer().notNull().default(0),
    demon: boolean().notNull().default(false),
    stars: integer().notNull().default(0),
    feature_score: integer().notNull().default(0),
    auto: boolean().notNull(),
    password: varchar().notNull(),
    upload_date: varchar().notNull().default("upload_date"),
    update_date: varchar().notNull().default("update_date"),
    copied_id: integer().notNull().default(0),
    two_player: boolean().notNull(),
    custom_song_id: integer().notNull().default(0),
    coins: integer().notNull(),
    verified_coins: boolean().notNull().default(false),
    stars_requested: integer().notNull(),
    unlisted: integer().notNull(),
    low_detail_mode: boolean().notNull(),
    daily_number: integer(),
    epic: integer().notNull().default(0),
    demon_difficulty: integer(),
    is_gauntlet: boolean().notNull().default(false),
    objects: integer().notNull(),
    editor_time: integer().notNull().default(0),
    editor_time_copies: integer().notNull().default(0),
    song_ids: integer().array().default([0]),
    sfx_ids: integer().array().default([0]),
    song_size: integer().notNull().default(0),
    verification_time: integer().notNull(),
    exact_upload_time: bigint({ mode: "number" }).notNull(),
    exact_update_time: bigint({ mode: "number" }).notNull().default(0)
});